// <auto-generated />
namespace HaberSitesi.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_addadminentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_addadminentity));
        
        string IMigrationMetadata.Id
        {
            get { return "202106261023347_mig_addadminentity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
