// <auto-generated />
namespace HaberSitesi.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_updatenewstitleandimage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_updatenewstitleandimage));
        
        string IMigrationMetadata.Id
        {
            get { return "202106240919527_mig_updatenewstitleandimage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
